frameworkVersion: ">=1.50.0 <2.0.0"

service: bydelsfakta-data-processing

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AmazonS3FullAccess
  environment:
    BUCKET_NAME: ok-origo-dataplatform-${self:provider.stage}
    GIT_REV: ${git:branch}:${git:sha1}
  tags:
    GIT_REV: ${git:branch}:${git:sha1}

plugins:
  - serverless-python-requirements
  - serverless-plugin-git-variables

resources:
  Description: >
    ${self:service} ${git:branch}:${git:sha1}

    ${git:message}

package:
  exclude:
    - "**/*"
  include:
    - 'common/*.py'
    - 'functions/*.py'

functions: ${file(serverless/functions.yaml)}

custom:
  layers:
    - { Ref: PythonRequirementsLambdaLayer }
  pythonRequirements:
    dockerizePip: non-linux
    layer: true
    usePoetry: false
  exportGitVariables: false
