frameworkVersion: ">=1.1.0 <2.0.0"

service: bydelsfakta-data-processing

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AmazonS3FullAccess

plugins:
  - serverless-python-requirements

package:
  exclude:
    - "**/*"
  include:
    - 'common/*.py'
    - 'functions/*.py'

functions: ${file(serverless/functions.yaml)}

custom:
  layers:
    - { Ref: PythonRequirementsLambdaLayer }
  pythonRequirements:
    dockerizePip: non-linux
    layer: true
    usePoetry: false
