service: bydelsfakta-data-processing

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  iamRoleStatements:
    - ${file(serverless/PutBucketNotification.yaml)}
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AmazonS3FullAccess

plugins:
  - serverless-python-requirements
  - serverless-plugin-existing-s3

package:
  exclude:
    - "./**"
  include:
    - '*.py'

functions: ${file(serverless/templates/rendered/functions.yaml)}

custom:
  layers:
    - arn:aws:lambda:eu-west-1:399891621064:layer:AWSLambda-Python37-SciPy1x:2 # numpy
    - arn:aws:lambda:eu-west-1:988529151833:layer:lambda-python-layers-Python37-Pandas23x:7 #pandas
    - arn:aws:lambda:eu-west-1:988529151833:layer:lambda-python-layers-Python37-bydelsfakta:2
  pythonRequirements:
    dockerizePip: non-linux
    fileName: requirements-deploy.txt
    pipCmdExtraArgs:
      - --no-deps